//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiduBusFiddler
{
    using System;
    using System.Collections.Generic;
    
    public partial class baidupoi
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public string uid { get; set; }
        public string type { get; set; }
        public string keyword { get; set; }
    }
}
